### ISSUE TITLE
Problem Statement N

### ISSUE THREAD

**Issue by ParnaviKulkarni** [Mozilla-Campus-Club-Cummins/Haktoberfest_Demo#14]
Write a program to check whether a number is a palindrome.
Case 1:
Input: 121 (Interger)
Output: 121 is a palindrome. (String)
Case 2:
Input: 123
Output: 123 is not a palindrome.

**Comment by Vis2306** [comment]
I would like to work on this problem statement.

**Comment by Vis2306** [comment]
Please check my solution

**Comment by ParnaviKulkarni** [comment]
This issue has been resolved.
